### ISSUE TITLE
key with utf-8 meaning generate no input.

### ISSUE THREAD

**Issue by vanicat** [pokepetter/ursina#209]
Hello,

I’m using an bépo keyboard, with an "é" key.

If I add 
```
def input(key):
    print(key)
```

then it will print standard key ('a',...) but not my 'é' key.

Thanks.

**Comment by pokepetter** [comment]
input has been changed to use raw keys, based on the physical position of the key. This means you should use QWERTY as a reference layout. This also means users won't have to rebind keys in order to enjoy your game with different a keyboard layout. If you for example have been using ZQSD for movement, you should change it to WASD.
For text input, like for example `é`, you can use `def text_input(key)` instead of `def input(key)`

**Comment by vanicat** [comment]
Thanks for the fix.
