### ISSUE TITLE
.FBX Model texture auto import

### ISSUE THREAD

**Issue by venaxyt** [pokepetter/ursina#315]
Hey, since I'm using Ursina I have to learn Blender too which is pretty difficult for a new user like for UV mapping texture shading etc.
As you probably already know it is possible to add a texture directly in a model like FBX by doing some manipulations so there is no need to import an external texture.
I was wondering if it could be possible to automatically import a FBX module texture without another file, for example Entiry(....model="myModel.fbx", texture="myModel.fbx").
I really think that it would be a very import thing to add to Ursina, much people is getting in trouble because of the non support of in-model textures.

Thanks for your help and for this beautiful project !

**Comment by pokepetter** [comment]
fbx is legacy, use gltf instead.

Also, I don't find it useful because:
1) I don't want to export the model from blender manually every time I make a change.
2) I don't make my textures in blender, and I don't think other people do either.
3) The source texture usually a .psd or .tiff so it wouldn't work without manually exporting it.

**Comment by venaxyt** [comment]
Ok thanks so could you send me a tutorial to just edit textures because I don't find how to.
Thanks for you speed support ;)
