### ISSUE TITLE
Some questions on lights and uvs

### ISSUE THREAD

**Issue by Spritekin** [pokepetter/ursina#33]
Hi,

I'm teaching my 12yo son a bit of graphics using python and found this project to be fantastic. I'm writing a tutorial for him that maybe I can provide to your project once cleaned up. The tutorial takes you step by step through multiple concepts like window creation, object creation, object movement, camera manipulation, hierarchies, textures and more.

However I have found problems with how to alter a vertices or UV coords in a mesh model (i.e. I create an entity with a cube model, then I want to alter the UVs for texture animations). If not possible, then how do I define a shader so I can programatically change the UVs on shader computation (so model is not affected). I can see a shader object but no references how to use it.

Another thing I can't find is a rendering mode. I would like to render the wireframe to explain how the meshes are built but can't find the option.

Finally, I can't find how to define the environment light, directional light, spot light, etc. I can see the entities have reflectiveness and all but can't find light info.

Help please?

Regards
Guimo

**Comment by Spritekin** [comment]
Ok so after some checking on the code, I found you support the setattr texture_offset and texture _scale in the Entity which allowed me to play with the UV.

That's one, but the other questions are still valid I guess.

Regards,
Guimo

**Comment by pokepetter** [comment]
**Altering a 3d model**
To change a model, just change it's attributes like .vertices, .triangles, .colors, .uvs, .normals, or .mode.
```python
e = Entity(model='cube')

# move vertices above the origin up 1, to make a capsule
for v in e.model.vertices:
    if v.y > 0:
        v.y += 1

e.model.generate() # call this to update the mesh

```
You can also create a Mesh by scratch if you want that.
If you set model.mode = 'line' and call model.generate() it will render it as lines, but
keep in mind it might not look exactly as expected it if it's mean to be solid.

To set window display_mode, set: 
`window.display_mode = 'wireframe' # render everything as wireframe`

You can also press F10 to toggle between default, wireframe, colliders, normals. F9 to return to default.

**UV Scrolling**
Modifying a Mesh instance and regenerating it every frame is not the best way to make texture scrolling, however.
It's too expensive to do that every frame so you can set 'texture_offset' and 'texture_scale' instead. I noticed they're not listed in the API reference and had actully forgotten about them myself. :P


**Lighting**
Lights are not really supported at the moment. The reflectivity is a work in progress as well, since I couldn't get it work like I wanted.
You can however take a look at panda3d's documentation and use the lights from there if you'd like.
Since ursina is made on top of panda3d you can always fall back to that control things at a lower level.
Often in games it's a good idea to bake the shadows anyway, as real-time shadows tend to multiply the draw calls. So I'm not really focusing on lighting a the moment.

There's a really basic shader called 'basic_lighting' you can use of you just want to see the shape of the model better. No cast shadows included, but at least it's not flat shaded. Or you could set window.display_mode = 'normals'. Keep in mind the model needs normals for these to work. If the model doesn't have them you can generate them with entity.model.generate_normals(). It can take whole to do that though, especially for bigger meshes.
