### ISSUE TITLE
The rendering froze after I tuned up the number of voxel

### ISSUE THREAD

**Issue by shamangary** [pokepetter/ursina#376]
As title. I am trying to make Minecraft more large-scale, but the process simply stopped after I increase the number of voxels.

```
# code example

ground_size = 224

for zi in range(ground_size):
    for xi in range(ground_size):
        voxel = Voxel(position=(xi, 0, zi))

rand_voxel_num = 2000
x = torch.randint(ground_size, (1, rand_voxel_num)).numpy()
y = torch.randint(ground_size, (1, rand_voxel_num)).numpy()
z = torch.randint(ground_size, (1, rand_voxel_num)).numpy()

for i in range(rand_voxel_num-1):
    voxel = Voxel(position=(x[0,i], y[0,i], z[0,i]))
```

The same computer is able to run normal Minecraft in a decent speed, so I think the hardware is fine.

Is there a way to render large-scale voxels?

**Comment by RedHenDev** [comment]
Yes, there is.

Basically, instead of creating an entity for each voxel, you can either 1) combine all the meshes of each entity into one or 2) extend the vertices of one entity's model as you go.

1) Make each entity a child of a single 'parent' entity. Then call .combine() on the parent entity's model. This destroys all the child entities and leaves you with just one single entity, but which now comprises your entire voxel terrain. The trick, though, is building up your terrain as you go, because combining lots of meshes like this is costly at run time.

2) Extending the vertex list of a model is a little more complicated, but does mean you can control the texture uvs of your terrain more easily. You can get very large terrains this way.

But really, for a truly massive terrain and to do things like Minecraft, you'd want to write an algorithm to only construct chunks of terrain from the surface vertices that actually protrude from the terrain -- for which you'd manually determine the positions of vertices and build your own mesh in the code, not load a premade mesh.

Here is a tutorial for the 2nd method -- a good balance between simplicity and getting larger terrains: [mesh terrain video tutorial](https://youtube.com/playlist?list=PLmP1LNMzp97rIbwnGHhjjobHHqWekxy8Yl)

**Comment by shamangary** [comment]
Thanks for the quick response. The link is not working but I found the youtube site of yours. [link](https://www.youtube.com/channel/UCmth-THBKWxLMw3aPsp-jQg) Thanks
