### ISSUE TITLE
How to use rigged models?

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#417]
I use ursina for a lot of my games, but can I used a rigged model, and control its movements? I have a .fbx file BTW.

Along with the rigged model, is it possible to import UVs in the form of a .tga?

**Comment by pokepetter** [comment]
From the FAQ:

How do I make a character animate?
You have two options here. The first one is using .glft files and panda3d's Actor:

```
from ursina import *
from direct.actor.Actor import Actor

app = Ursina()

entity = Entity()
#animations are stored within the file
actor = Actor("filename.gltf")
actor.reparent_to(entity)

actor.play("animation_name")

app.run()
```
See the panda3d documentation for more info.

The second option is to use FrameAnimation3d. For that you need a sequence of models that can be loaded by ursina.
So if you have some frames named run_cycle_000.obj, run_cycle_001.obj, run_cycle_002.obj and so on,
you can load it like this:
```
FrameAnimation3d('run_cycle_')
```

You might be able to use fbx files too, but it's a proprietary format and is not the standard anymore. Textures should get imported too, since they can be included in glft/glb files, as far as I know.

You can no import UVs in the form of a .tga, since the image does not contain uvs. The model does. But ursina can import .tga files, yes.

**Comment by ShadityZ** [comment]
Thanks for all the help! I'll look into it and tell you how I go.

**Comment by ShadityZ** [comment]
I have been having some problems, so I decided to use the FrameAnimation3d(), and it works great! Thanks for all the help PokePetter!
