### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by AndreMiras** [pokepetter/ursina#43]
Looks like a cool project. How about publishing to PyPI before someone else squats that name?
Edit:
Also until it gets published to PyPI, you can update the install instructions to:
```sh
pip install https://github.com/pokepetter/ursina/archive/master.zip
```
Not only it skips the `git` system dependency but also installs faster as it skips the cloning

**Comment by pokepetter** [comment]
Oh, I didn't know you could do that. I'll change it to the .zip then ^^

The reason I haven't published to PyPI is that it's so much work. I have to log in, upload it, and then it doesn't work because I didn't increment the version number or something. It's just too complicated and I gave up. If there's a way to making it as easy and automatic as the one click it is to push to the git repo, I'm listening.

**Comment by AndreMiras** [comment]
Thanks for getting back :)
Yes there's a way to make it much easier through the CI. Once this way is in place (I can pull request it) all it would require you is to indeed update the `setup.py` version and push a tag to your remote repo. We can have a live chat, like on Discord or somewhere else to go through it.
I think it's really worth it because it would really simply user experience and also you would get quite annoyed if someone else took `ursina` on PyPI

**Comment by pokepetter** [comment]
It's on PyPi now. Now that things don't break as often, I will be uploading LTS versions on PyPi and it will be the main way to install as well.
