### ISSUE TITLE
Performance issues for a larger amount of Entities

### ISSUE THREAD

**Issue by famecastle** [pokepetter/ursina#45]
Unfortunately, I'm unable to create a Voxel-game, because there are so many cube entities (13,000) that the game gets really slow.

Generating Entities is generally slow (due to the fact that you use `inspect.[...]` functions in entity.py which make the code slow).

But we can live with longer loading times. However, the rendering speed is generally quite slow. I suppose this is due to Panda3d. It can handle few meshes with many polygons much better than many meshes with few polygons. For that reason, there is the `RigidBodyCombiner` which intelligently combines meshes just before they're being rendered.

I've written this Ursina Binding:
```from ursina import Entity
from panda3d.core import RigidBodyCombiner, NodePath, Vec3
import random

class EntityCombiner(Entity):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.rbc = RigidBodyCombiner("rbc")
        self.rbcnp = NodePath(self.rbc)
        self.rbcnp.reparentTo(self)

        self.rbc.collect()
    
    def add(self, entity):
        entity.reparentTo(self.rbcnp)
    
    def update_items(self):
        self.rbc.collect()
```

It does improve the framerate, drastically indeed. But at the same time, removing Entities or setting their shaders doesn't show on the screen anymore, because I suppose that we'd have to call `self.rbc.collect()` in that case, which, in turn, is slow again and not desirable for regular view updates.

I think, a good performance for screens filled with thousands of similar objects, is quite important! Any idea on how to improve the performance?

**Comment by pokepetter** [comment]
I'll make it so it doesn't use trace by default, since it's for a debugging feature.
Entities are mainly intended to only be a handful of and trade performance for usability, but you can make them a bit faster by not adding them to scene.entities by passing add_to_scene_entities=False.

I see the RigidBodyCombiner is intended to increase performance with many *moving* NodePaths. If they are static, you're better off having chunks where the blocks are not separate at all, but a combined mesh. There are also lot's of specific tricks you can use when it's voxel based world.
