### ISSUE TITLE
French keyboard

### ISSUE THREAD

**Issue by spe-nsi** [pokepetter/ursina#509]
Hi,
I've been using a code learning activity with Ursina for 2 years but now the keyboard mapping doesn't seem to be the french one configured in my OS anymore.
(I placed `print(key)` in the `input` function and a hit on the key "m" doesn't print anything but the key "k" for example works).
Is there a keyboard layout configuration function anywhere ?

**Comment by pokepetter** [comment]
This has been changed so the developer should assume qwerty. Now it's based on the physical location of the keys. 
There was this big problem before where every user who didn't have the same layout as the developer would have to rebind. For example, the FirstPersonController wouldn't work on french keyboard because it was programmed to use the wasd keys.

The function `text_input(key)` has been added and works like input did before. However, it's intended for entering text, not gameplay.
