### ISSUE TITLE
How to stop entities going thru other entities.

### ISSUE THREAD

**Issue by fesfgew** [pokepetter/ursina#54]

**Comment by DiamondsBattle** [comment]
Add the collider='entity_model' to the Entity, wich will add to it a 'hitbox'.
`my_entity = Entity(model='cube', collider='cube') # This will add the hitbox`
For other questions, you should head on the [Discord Server](https://discord.gg/s3PV83Z).

**Comment by fesfgew** [comment]
thank you

**Comment by fesfgew** [comment]
didn't work

**Comment by DropBear586** [comment]
Collision detection isn't straightforward unfortunately.
You need the "hitbox" or collider and a raycast. Think of it as a laser which you shoot in a direction for a specific distance and check if it returns a hit on a objects collider, if so, do something. 
Check out the documentation of the webpage for some examples and keep an eye out on the discord as Im making a more simpler collider detection which involves coordinates rather than the collider and ray cast.

**Comment by fesfgew** [comment]
thank you

**Comment by pokepetter** [comment]
The first step is to add a collider. See here: https://www.ursinaengine.org/cheat_sheet.html#Collider
And then to raycast: https://www.ursinaengine.org/cheat_sheet.html#raycaster
The raycast will then return a HitInfo: https://www.ursinaengine.org/cheat_sheet.html#HitInfo

Here's how I do in in the FirstPersonController, in its update function:
```python
self.direction = Vec3(
    self.forward * (held_keys['w'] - held_keys['s'])
    + self.right * (held_keys['d'] - held_keys['a'])
    ).normalized()

middle_ray = raycast(origin , self.direction, ignore=[self,], distance=.25, debug=False)

if not middle_ray.hit:
    self.position += self.direction * self.speed * time.dt
```

**Comment by pokepetter** [comment]
You can also use entity.intersects() to check if its collider intersect other colliders.
