### ISSUE TITLE
API docs look odd

### ISSUE THREAD

**Issue by pvcraven** [pokepetter/ursina#62]
I'm running on Windows. Went here:
https://www.ursinaengine.org/cheat_sheet.html#Audio

Docs look weird on Firefox and Chrome:
<img width="566" alt="2020-08-03_11-29-24" src="https://user-images.githubusercontent.com/1463116/89205096-c5d5b700-d57c-11ea-9f66-7b3b118dc3b5.png">

**Comment by pokepetter** [comment]
Turns out this only happens if you're on a small screen like on a laptop. You should be able to just scroll left to fix it, but it will reset every time you use the sidebar for some reason. There was also an incredibly long line of code in one of the examples which I I've now changed.

I've changed white-space to pre-wrap for now, to eliminate horizontal scrolling altogether.
