### ISSUE TITLE
Official pronunciation? 

### ISSUE THREAD

**Issue by ChildishGiant** [pokepetter/ursina#9]
Some FOSS projects with odd names have a pronunciation in the readme. Either using [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) or sounding it out like err-seen-a

**Comment by clayboone** [comment]
This is how I pronounce it. The "err" part is like the "-rrr" part of "Lrrr from Omicron Percia 8" rather than in "To err is human..." And the "-a" sounds more like the "uh" verbal pause than the first part of the word "eight."

Seconded for "rrr-seen-uh."

I'd also be okay with "rrr-sihn-uh" with a soft _i_, but English idioms suggest pronouncing it the first way.

**Comment by clayboone** [comment]
I spoke with an English-native British national at work about this and his first attempt was the second variant in my previous comment: the one with the soft _i_.

@pokepetter How do you feel about "rrr-sihn-uh" for inclusion somewhere in the readme's or docs?
